### ISSUE TITLE
Local & Remote?

### ISSUE THREAD

**Issue by kamronbatman** [objectify/objectify-remotely#2]
Is there an easy way to modify this (and maybe Objectify too) in order to support a local and remote datastore?

I ask because we have an admin server for games, and we might decide to use a local datastore for admin related stuff in addition to the game server's datastore.

Thanks!

**Comment by stickfigure** [comment]
I don't understand the question - this library lets you control whether a request goes to a local or remote datastore. What else do you want to see?

**Comment by kamronbatman** [comment]
I thought I saw somewhere that you could only use this for a remote -or- a local datastore.
I also couldn't find any examples of using it with a local -and- a remote datastore.

I might need to just be pointed in the right direction! :)
